### ISSUE TITLE
Parsing message dump failed...Segmentation fault

### ISSUE THREAD

**Issue by Yangns** [CESNET/libnetconf#126]
Hi,
We have tried giving a request to netopeer without using SSH connection. We inserted a user defined function ```nc_invoke()``` in main() function of server.c. In ```nc_invoke()```, we have written the following code:
```
nc_rpc* x;
nc_rpc** y;
void nc_invoke()
{
char c[]="some rpc request";
y=&x;
x=nc_rpc_build(NULL, c);
nc_session_receive(NULL, 100000, y);
}
```

Here, the control is going to ```nc_msg_build()``` from ```nc_rpc_build()```. There, in ```nc_msg_build()```, we are getting an error at ```xmlReadMemory()``` : ```nc_msg_build: parsing message dump failed```. 
when we printed the output of xmlReadMemory(), it returned null value.

Sample request:
```
<?xml version="1.0" encoding="utf-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
  <get />
</rpc>
```

Please help us out.
It would be thankful if you tell us the reason why ```xmlReadMemory()``` is used.

**Comment by rkrejci** [comment]
It is simple, you are getting NULL, because you are saying to nc_rpc_build() that RPC is NULL. See the [nc_rpc_build() doc](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/db/de9/group__rpc.html#ga5c4348c96b0d5e6a64f94dbbdeaf4100). And neither the rest of your code make any sense. You are using nc_session_receive() (btw, it is a static function and to use it you had to modify libnetconf source code and you should really know what you are doing) with wrong parameters and for some magic reason which is very unclear to me.

xmlReadMemory is used to build XML tree from string. That's simply its functionality.
