### ISSUE TITLE
Is custom datastore supported?

### ISSUE THREAD

**Issue by tomdenesyk** [CESNET/libnetconf#127]
Hi Michal
From the issues history it would seem the answer is 'No'.

But I've been browsing the code, and I see some hooks. So may be the answer is 'Sort of.'

Please comment.

Thanks,
Tom

**Comment by rkrejci** [comment]
Well, the prefered way of customizing libnetconf (netopeer) to some device is a transAPI module. But we are aware that it does not cover all needs and therefore there is custom datastore. So, it IS supported, but:
- there is no "plugin" way for custom datastore implementation in Netopeer server. You have to modify the server (or write it from scratch).
- documentation is not so rich as in case of transAPI, but some info you can find [here](https://rawgit.com/CESNET/libnetconf/master/doc/doxygen/html/d1/deb/datastores.html) and example of custom datastore implementation can be found in [of-config project](https://github.com/openvswitch/of-config).
- custom datastore implementation is very complex, since it requires from you to implement NETCONF edit-config operation on your data representation.

Anyway, in libnetconf2 we plan to change/unify these approaches and things should be more simple (with no custom datastore implementation needed).

**Comment by tomdenesyk** [comment]
Tell me about libnetconf2.
What does the schedule look like?
What stage are you at?
Regards,
Tom




Sent from my Samsung Galaxy Tab®4


-------- Original message --------

**Comment by rkrejci** [comment]
The plan is to have current libnetconf functionality during the next year. Some working (with basic NETCONF functionality) version should be available in the middle of the next year. 

We already have NETCONF communication (sending/receiving NETCONF messages, establishing NETCONF session) and we are designing how the NETCONF datastore (including some API for applications, i.e. something like custom datastore and transAPI) should look like. The code is not yet public, but it is still supposed to be open source under BSD license.
