### ISSUE TITLE
How do you send an event to a stream created with ncntf_stream_new?

### ISSUE THREAD

**Issue by calciajd** [CESNET/libnetconf#129]
How do you send an event to a stream created with ncntf_stream_new? The only examples I can find anywhere just follow the format of 
`ncntf_event_new(-1, NCNTF_GENERIC,  "<example-event xmlns=\"some:namespace\"><msg>Hey!!! Something happened!</msg></example-event>");`

and that seems to only send to the default NETCONF stream. I feel like I'm missing the way to specify a user created stream.

Thanks for any help you can give.

**Comment by rkrejci** [comment]
When you create new event stream, just set event rules (which events will be stored in this stream) for this stream via `ncntf_stream_allow_events()`:
```
ncntf_stream_allow_events("mynewstream", "example-event");
```

The issue I see here now is that it ignores namespaces, so if there will be another `example-event` in some other namespace, it will be also stored into `mynewstream`. Due to work on libnetconf2, I'm not in favor to fix this by changing libnetconf API, are you ok with this?

**Comment by rkrejci** [comment]
Another issue with event notifications is that ALL events are stored in default NETCONF stream. So even after using `ncntf_stream_allow_events()`, your `example-event` will be available also in NETCONF stream. RFC is not clear about this, but there was a discussion in IETF and NETCONF stream is supposed to be used by default (if no other is specified), not always.

**Comment by calciajd** [comment]
That works. Perhaps the doc for ncntf_stream_allow_events or ncntf_stream_new could be updated to reference the need for both functions.
Thank you!
