### ISSUE TITLE
validation callbacks

### ISSUE THREAD

**Issue by andre-brizido** [CESNET/libnetconf#148]
Hi

Do you plan to have validation callbacks? Sometimes the validations contained in the models are not enough, so it would be useful to have validation callbacks. It would also be useful that they run before any configuration callback from any module.

Also, are you thinking in some way of dealing with precedences (besides the root to leaf)? 
Example:
The interface model was augmented by some other model with a learef to a profile contained in that model. In this case:
- If you want to associate a profile to an interface, first you must create the profile on the device and then associate the profile to the interface
- If you want to remove the profile, then you must first remove the association to the interface and then remove the profile on the device.
As you can see, if you have 1 callback associated to the leafref of the interface and another to the profile, then the order depends of the operation.

Best regards

**Comment by rkrejci** [comment]
Hi,
such a validation can be added into transAPI callback. There are no validation-specific callbacks that would be called before any configuration (transAPI) callback. I understand that issue is that with standard transAPI callbacks the rollback must be performed when validation fails. Since we are not going to add new features into libnetconf, we don't plan to add such callbacks.

However, we are working on new generation of NETCONF tools and the new datastore implementation ([sysrepo](https://github.com/sysrepo/sysrepo)) should have such callbacks and also there should be some mechanism to set order of callbacks. But it is still a work in progress.
