### ISSUE TITLE
Implementation of structural mount-point

### ISSUE THREAD

**Issue by smitagitbuh** [CESNET/libnetconf#181]
Need some inputs for implementing the structural mount-point draft. 
https://datatracker.ietf.org/doc/draft-bjorklund-netmod-structural-mount

With the current YANG 1.0 or the libnetconf 0.10, it doesn't seem to have any feature support for the mounting schema into another schema.

Appreciate any pointers regarding how this can be achieved? How the Yang can be mounted and validated on the runtime?
Are there any plans to have any such functionality in near future?

Thanks
Smita

**Comment by rkrejci** [comment]
I'm not sure what you want to do. Are you going to extend libnetconf by support for the structural mount?

libnetconf currently does not support this feature and there are no plans to implement it in near future. Actually because of our work on [libyang](https://github.com/CESNET/libyang) and [libnetconf2](https://github.com/CESNET/libnetconf2) we are not going to implement any new feature into libnetconf.

I'm afraid that because of using DSDL for validation in libnetconf, this would be a complex change that would include changes in the process how the DSDL files (RNG and Schematron) are generated for libnetconf.

I can image support for this mechanism in libyang, but there is currently no plan (and no resource) to implement it.
