### ISSUE TITLE
There is not enough space to monitor another NETCONF session.

### ISSUE THREAD

**Issue by Yangns** [CESNET/libnetconf#186]
Hi,

While trying to establish multiple sessions using one libnetconf and multiple netopeers, we are getting the below error...

```
if ((totalsize + litem->size + size) > session_list->size) {
      ERROR("There is not enough space to monitor another NETCONF session.");
      pthread_rwlock_unlock(&(session_list->lock));
      return (EXIT_FAILURE);
}
```

Please help us to overcome this....
Thank you in advance.

**Comment by michalvasko** [comment]
Hi,
it usually is enough, so we will not fix this in master libnetconf, but you can easily increase the size of the `session_list` in your libnetconf. Just modify the macro `SIZE_STEP` in session.c:190. Currently there is 16kb allocated and one session should take approximately 200b, did you really have more than 80 sessions? Because if not, then there is some other problem.

Regards,
Michal

**Comment by ntadas** [comment]
Hi

I also have this problem if I try to establish 100 sessions with the user name administrator.
I understand that 100 sessions is not likely to happen but couldn't we change a little the code to allow the user to define the STEP_SIZE in compile time? 
This way you can continue to have the lib with the 16k by default but if someone wants/needs it can increase it without patching the code.

Just a suggestion, as you mention above the patch is also easy.

Best Regards

**Comment by rkrejci** [comment]
usage:
```
MONITORING_LIST_SIZE=32 ./configure
```

You could be more nice to us next time, such an easy change could be provided as pull request ;-)

**Comment by ntadas** [comment]
agree, will do next time, thanks a lot.
