### ISSUE TITLE
Publishing to package management system?

### ISSUE THREAD

**Issue by abhikeshav** [CESNET/libnetconf#210]
Hi,
Any plans on publishing libnetconf to any of the Linux package management systems (apt or yum)?

Thanks

**Comment by rkrejci** [comment]
Hi, no plans in this area. We are currently working on the next generation of the NETCONF tools, so maybe in case of [libyang](https://github.com/CESNET/libyang), [libnetconf2](https://github.com/CESNET/libnetconf2) and [Netopeer2](https://github.com/CESNET/Netopeer2), but there are no specific plans in this area. 

The problem is that it would probably require some additional resources (time) for supporting "another distribution channel" besides the github.
