### ISSUE TITLE
Why libnetconf does not follow the configuration handling as per user given order in the request

### ISSUE THREAD

**Issue by pd45169** [CESNET/libnetconf#219]
Hi,

It is observed that libnetconf always follow its internal order while executing config request. If user has given edit request for multiple data models and it has inter-dependency among the models, it becomes a problem.

Is there any way user can execute the edit request in same the sequence as given in edit-request.

Thanks.

**Comment by rkrejci** [comment]
this is not the issue of the order of executing changes, but the issues of the dependency among the models. libnetconf is not ready e.g. for leafrefs from one model to another. This is a design issue because libnetconf stores data of each model in a separated files and handles this data separately.

The issue is solved in the new generation of our NETCONF tools - [libyang](https://github.com/CESNET/libyang), [libnetconf2](https://github.com/CESNET/libnetconf2) and [Netopeer2](https://github.com/CESNET/Netopeer2).

**Comment by pd45169** [comment]
Thanks.
