### ISSUE TITLE
our new project need to implement a neconf service device, i saw some document ,but, i still confused to chosse libnetconf or libnetconf2.

### ISSUE THREAD

**Issue by RogerYaozhenyu** [CESNET/libnetconf#251]
As the README mentioned , libnetconf2 is more efficient  but some service side fucntions not fully supported.  our device has a DB module, so it seems like we should develop a  netconf to  DB adaptor
module . if we don't care datastore funtion,  Is the libnetconf2  more better to our project?  
or could you give your opinion? thanks

**Comment by rkrejci** [comment]
The main point in the README is that libnetconf2 implements only the NETCONF transport and manipulation with the messages. It does not implement operations like `<get>` or `<edit-config>` because they need to be applied to the configuration data in the NETCONF datastore which is not part of libnetconf2. 

So, if you are able to implement NETCONF server with e.g. NETCONF session management and apply NETCONF operations to the server (session and datastore management (lock, unlock, kill-session, notifications) and configuration data (edit-config, get, ...)), you should be fine with libnetconf2.
