### ISSUE TITLE
Freebsd, make returns error

### ISSUE THREAD

**Issue by mirza-ubaid** [CESNET/libnetconf#270]
Freebsd 11.1 x64 VirtualBox:
./configure ended without any error. 
when I run make it returns: 
![make](https://user-images.githubusercontent.com/33876457/36975406-cd88da10-209b-11e8-9f0c-e83e4bcecc39.png)

**Comment by michalvasko** [comment]
Hi,
libnetconf never supported FreeBSD so errors are expected. Also, libnetconf itself is no longer supported, if you plan to port something on FreeBSD, it should be [libnetconf2](https://github.com/cesnet/libnetconf2).

Regards,
Michal

**Comment by mirza-ubaid** [comment]
Used gmake instead and it worked.
Freebsd libc is missing shadow.h that causes make to fail for libnetconf2. I not able to find a way to get libshadow for freebsd.

**Comment by michalvasko** [comment]
Hi,
there is no `libshadow`, you would have to rewrite the mechanism of how system usernames and passwords are retrieved. I think it is still preferable to using this old *libnetconf* because you will not get any support for this. All the common use-cases should be working but anything slightly advanced or recent will not work and it will only get worse in time.

Regards,
Michal
