### ISSUE TITLE
"when" statement implementation

### ISSUE THREAD

**Issue by Adrian2009** [CESNET/libnetconf#76]
according to RFC6020 8.3.2, during <edit-config>processing, if the "when" condition is false, the server needs to delete the configuration, does libnetconf implement according to it?

"If the NETCONF operation modifies a data node such that any node’s
"when" expression becomes false, then the node with the "when"
expression is deleted by the server."

**Comment by rkrejci** [comment]
No, libnetconf itself does only small part of validation, the most part is done by external DSDL tools, so libnetconf (via these tools) only detects that there is something wrong and returns validation error. In case you switch off validation (using 'set' value of edit-config's 'test-option' or in case there are no DSDL files available), the most validity rules defined by YANG language are ignored.

This issue should be solved by replacing libxml2 by [libyang](https://github.com/CESNET/libyang), we are currently working on, because libyang integrates validation so far being done by external DSDL tools.
