### ISSUE TITLE
Why not use callhome without libssh ?

### ISSUE THREAD

**Issue by wirelessr** [CESNET/libnetconf#79]
Hi,

I saw the APIs of callhome is disabled when "--disable-libssh".

If I want to enable them with TLS, what should I do?

**Comment by michalvasko** [comment]
Hi,
I am afraid this is not possible. SSH support is mandatory and cannot be completely turned off. When you don't want to use libssh, you can still get basic SSH functionality (using ssh(1) utility), but not Call Home, because it cannot be implemented using ssh(1).

You can look into netopeer, which implements Call Home differently, not using these functions in libnetconf and enables to have TLS-only NETCONF server witch Call Home.

Regards,
Michal

**Comment by wirelessr** [comment]
Do you mean netopeer-server can be a TLS-only client with Call Home?

How about netopeer-cli? Can it be a TLS-only server?

**Comment by michalvasko** [comment]
Hi,
the terminology is a bit confusing, so I'll try to word everything carefully. netopeer-server CAN support initiating Call Home connections even if libnetconf was compiled WITHOUT libssh. netopeer-cli CANNOT support accepting Call Home connection if libnetconf was compiled WITHOUT libssh since it uses the libnetconf Call Home API.

Regards,
Michal

**Comment by wirelessr** [comment]
Hi,
I really appreciate your explanation.
