### ISSUE TITLE
For an edit-config message, if puts a create operation on a leaf, the validation fails

### ISSUE THREAD

**Issue by classcwnd** [CESNET/libnetconf#83]
When send edit-config with a "create operation" on the leaf <econtext:vpn-rd>, the validation fails. 
All configuration in the edit-config NETCONF message are new.
I dumped out the configuration document which is the input doc for validate_ds(), and found the xml doc is wrong.  
I think there might be something wrong in editconfig() of libnetconf for this case.
I also send an edit-config message without "create operation", and the validation succeed.

Edit-config Message with "create operation" on a leaf: 
```
<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="106"
     xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
     xmlns:econtext="urn:ietf:params:xml:ns:yang:my-context"
     xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config">
  <edit-config>
    <target>
      <running/>
    </target>
    <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <econfig:contexts>
        <econtext:context>
          <econtext:context-name>test2</econtext:context-name>
           <econtext:vpn-rd xc:operation="create">121:1112</econtext:vpn-rd>
        </econtext:context>
      </econfig:contexts>
    </config>
  </edit-config>
</rpc>
]]>]]> 
```

Input doc for validate_ds():  
There is no prefix for both "contexts" and "context" and there are two "context" included in "contexts", which is wrong.
```
<?xml version="1.0"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><contexts xmlns="urn:ietf:params:xml:ns:yang:my-config"><context xmlns="urn:ietf:params:xml:ns:yang:my-context"><econtext:vpn-rd xmlns:econtext="urn:ietf:params:xml:ns:yang:my-context">121:1112</econtext:vpn-rd></context><econtext:context xmlns:econtext="urn:ietf:params:xml:ns:yang:my-context"><econtext:context-name>test2</econtext:context-name></econtext:context></contexts></data>
```

Edit-config Message without "create operation" on leaf:
```
<?xml version="1.0" encoding="UTF-8"?>
<rpc message-id="106"
     xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"
     xmlns:econtext="urn:ietf:params:xml:ns:yang:my-context"
     xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config">
  <edit-config>
    <target>
      <running/>
    </target>
    <config xmlns:xc="urn:ietf:params:xml:ns:netconf:base:1.0">
      <econfig:contexts>
        <econtext:context>
          <econtext:context-name>test2</econtext:context-name>
          <econtext:vpn-rd>121:1112</econtext:vpn-rd>
        </econtext:context>
      </econfig:contexts>
    </config>
  </edit-config>
</rpc>
]]>]]>
```

Input doc for validate_ds():
```
<?xml version="1.0"?>
<data xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><econfig:contexts xmlns:econfig="urn:ietf:params:xml:ns:yang:my-config" xmlns:econtext="urn:ietf:params:xml:ns:yang:my-context"><econtext:context><econtext:context-name>test2</econtext:context-name><econtext:vpn-rd>121:1112</econtext:vpn-rd></econtext:context></econfig:contexts></data>
```

**Comment by michalvasko** [comment]
Hi,

this seems to be a design problem of how the edit config is applied on a datastore and would require considerable amount of effort to fix. We are unlikely to do so, mainly, because your edit config document with the create element does not really make much sense. The problem should occur only when you're creating the whole context, so create should be on the context, not on the leaf.

Regards,
Michal

**Comment by classcwnd** [comment]
Hi Michal,

But this doesn't break the rule of rfc. I think this is a limitation of libnetconf?

Thanks,
Yu

**Comment by michalvasko** [comment]
Hi Yu,

yes, this is a limitation of the current libnetconf. We are planning libnetconf2, which should be significantly improved version of libnetconf including having no design faults such as this, but that will take a considerable amount of time. Until then there is libnetconf, which should work well under standard correct conditions.

Regards,
Michal

**Comment by jinxud** [comment]
Hi,

can we make below change to fix the problem:
update edit_operations() function: to do merge operation before create operation? 

	/* merge operations */
	nodes = get_operation_elements(NC_EDIT_OP_MERGE, edit_doc);
	if (nodes != NULL) {
		if (!xmlXPathNodeSetIsEmpty(nodes->nodesetval)) {
			/* something to create */
			for (i = 0; i < nodes->nodesetval->nodeNr; i++) {
				if (edit_merge(orig_doc, nodes->nodesetval->nodeTab[i], defop, model, keys, nacm, error) != EXIT_SUCCESS) {
					xmlXPathFreeObject(nodes);
					goto error;
				}
				nodes->nodesetval->nodeTab[i] = NULL;
			}
		}
		xmlXPathFreeObject(nodes);
	}

	/* default merge */
	if (defop == NC_EDIT_DEFOP_MERGE || defop == NC_EDIT_DEFOP_NOTSET) {
		/* replace whole document */
		if (edit_doc->children != NULL) {
			for (edit_node = edit_doc->children; edit_node != NULL; edit_node = edit_doc->children) {
				if (edit_merge(orig_doc, edit_doc->children, defop, model, keys, nacm, error) != EXIT_SUCCESS) {
					goto error;
				}
			}
		}
	}
	
	
		/* create operations */
	nodes = get_operation_elements(NC_EDIT_OP_CREATE, edit_doc);
	if (nodes != NULL) {
		if (!xmlXPathNodeSetIsEmpty(nodes->nodesetval)) {
			/* something to create */
			for (i = 0; i < nodes->nodesetval->nodeNr; i++) {
				if (edit_create(orig_doc, nodes->nodesetval->nodeTab[i], defop, model, keys, nacm, error) != EXIT_SUCCESS) {
					xmlXPathFreeObject(nodes);
					goto error;
				}
				nodes->nodesetval->nodeTab[i] = NULL;
			}
		}
		xmlXPathFreeObject(nodes);
	}

**Comment by michalvasko** [comment]
Hi,

you found where the problem is, but it is not that simple to solve (that's what I wrote). Specifically, every operation is applied separately, which causes all the trouble in conjunction with lists and their keys.

Having Yu's edit-config, your solution would not fix the problem. You first apply merge and create new context with the key context-name "test2" in effect. Then you apply create. However, the config for this operation is left without the key and because of that a new context is created with vpn-rd node, but without the key. The solution that comes to my mind and would correct this behavior is first transforming the operations into actual operations that will get executed (in our case changing the default merge operation of all the nodes except vpn-rd to create) and then applying it like now (it may be necessary to adjust the order somehow). But that would require significant effort which we will rather devote to our current projects, which should ultimately result in an improved libnetconf.

Regards,
Michal

**Comment by jinxud** [comment]
Hi,

Could you share a little bit why there are 2 contexts in input doc for validate_ds()?


Thanks,
Jin

**Comment by michalvasko** [comment]
Hi Jin,

I tried to briefly explain this in my previous post. The nodes with the merge operation (basically just "context-name") are applied separately of the nodes to be created ("vpn-rd") and thus breaking the list-key relationship. First the context with "context-name" is created, which is the result of performing the merge. Then the "vpn-rd" node is created as follows. Actually, this whole config can be considered invalid, because it's missing the key. Nevertheless, libnetconf tries to find the correct position for it. It searches for context and finds only one with the key "test2" that was added in the first step. This does not match the key in this second config (none) so libnetconf proceeds to create another context for this "vpn-rd" node. Like I have said a few times already, this is a design flaw and we are working to resolve this, but it will take some time.

Regards,
Michal
