### ISSUE TITLE
The design intention of disconnecting client when failed to decode RPC message

### ISSUE THREAD

**Issue by luowei-eric** [CESNET/libnetconf#87]
Hi,

When failed to decoding a RPC message, the server would close the session which sent the bad RPC. Is this the design intention to compliance with RFC6242, or just for simple? Can it be changed to a more error tolerate way?

The related definition in RFC6242:
4.2.  Chunked Framing Mechanism
...
   If the chunk-size and the chunk-size value respectively are invalid
   or if an error occurs during the decoding process, the peer MUST
   terminate the NETCONF session by closing the corresponding SSH
   channel.  Implementations MUST ensure they are not vulnerable for a
   buffer overrun.

Thanks,
Wei

**Comment by michalvasko** [comment]
Hi Wei,

I don't understand your issue here, we try to follow RFCs as much as we can, but some wrong early design decisions prevent us from achieving full compliance all the time (should be remedied by libnetconf2). This is a case which is strictly mentioned in the RFC, as you noticed, so no, it cannot be changed to be more tolerable.

Regards,
Michal
