### ISSUE TITLE
Validation Failure - leafref inside typedef used in augmentation or another module

### ISSUE THREAD

**Issue by hiharikp** [CESNET/libnetconf#92]
There is a leafref type inside a typedef.
This typedef has used in the augmentation.
edit-config is failing on the augmentation leaf.

There are two simple yang models student.yang and college.yang
student.yang is augmenting college.yang
edit-config on this augmentation leaf (best-student-name) is failing, though John student exist.
Error Message:
Datastore fails to validate: Leaf "/nc:config/stud:students/stud:student/stud:name" does not exist for leafref value "John"

```
module college {

    namespace "http://www.abc.com/ns/college";
    prefix "clg";

    organization 
    "TBD";

    revision 2014-09-18 {
        description "Initial revision.";
    }
        
    container college-info {
    
		container award-info {
			leaf award-name {
				type string;
			}		
		}	
    }   
}    
```
```
module student {

    namespace "http://www.abc.com/ns/student";
    prefix "stud";

    import college {
        prefix clg;
    }
  
    organization 
    "TBD";

    revision 2014-09-18 {
        description "Initial revision.";
    }

	typedef stud-name-ref {
		type leafref {
			path "/stud:students/stud:student/stud:name";
		}
	}

    container students {
		list student {
			key name;
			leaf name {
				type string;
			}
		}
    }      
    
	augment "/clg:college-info/clg:award-info" {  
		leaf best-student-name {
			type stud:stud-name-ref;
		}				
	}
}    
```

Software Version:
{
libnetconf (mainline) - 30 July 2015
netopeer (mainline) - 30 July 2015
Linux
}

**Comment by rkrejci** [comment]
libnetconf validates data using DSDL (RelaxNG + Schematron) via external tools. The problem with augmentation is that you have to generate validator files (*-config.rng and *-schematron.xsl) for both (the base and augmenting) modules together:
```
lnctool --model college.yang --augment-model student.yang validation
```

Then the validation should work with the best-student-name. The problem here is, that when you removes the augmenting module from the server, you would have to regenerate the validator files to reflect such a change. Similarly, when you disable/enable some feature, you should regenerate the validator files specifying which features are enabled/disabled.

**Comment by hiharikp** [comment]
I have run lnctool the same way mentioned above. rng and schematron files generated properly.
We are seeing the issue because of the below RULE in college-schematron file.

===================================
<axsl:template match="/nc:config/clg:college-info/clg:award-info/stud:best-student-name" priority="1000" mode="M6"><svrl:fired-rule xmlns:svrl="http://purl.oclc.org/dsdl/svrl" context="/nc:config/clg:college-info/clg:award-info/stud:best-student-name"/>

<axsl:if test="not($root/stud:students/stud:student/stud:name=.)"><svrl:successful-report xmlns:svrl="http://purl.oclc.org/dsdl/svrl" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:schold="http://www.ascc.net/xml/schematron" test="not($root/stud:students/stud:student/stud:name=.)"><axsl:attribute name="location"><axsl:apply-templates select="." mode="schematron-get-full-path"/></axsl:attribute><svrl:text>Leaf "/nc:config/stud:students/stud:student/stud:name" does not exist for leafref value "<axsl:text/><axsl:value-of select="."/><axsl:text/>"</svrl:text></svrl:successful-report></axsl:if><axsl:apply-templates select="*|comment()|processing-instruction()" mode="M6"/></axsl:template><axsl:template match="text()" priority="-1" mode="M6"/><axsl:template match="@*|node()" priority="-2" mode="M6"><axsl:apply-templates select="*|comment()|processing-instruction()" mode="M6"/></axsl:template>
===================================

**Comment by hiharikp** [comment]
I am seeing the same problem even without augmentation.
Error:
Datastore fails to validate: Leaf "/nc:config/stud:students/stud:student/stud:name" does not exist for leafref value "John"

module student {

    namespace "http://www.abc.com/ns/student";
    prefix "stud";

	typedef stud-name-ref {
		type leafref {
			path "/stud:students/stud:student/stud:name";
		}
	}

    container students {
		list student {
			key name;
			leaf name {
				type string;
			}
		}
    }      
}    

module college {

    namespace "http://www.abc.com/ns/college";
    prefix "clg";

	import student {
		prefix stud;
	}
       
    container college-info {
    
		container award-info {
			leaf prev-stud-name {
				type stud:stud-name-ref;
			}		
		}	
    }   
}    

![schematron_rule_noaugment](https://cloud.githubusercontent.com/assets/13743705/9193905/cdb733dc-4034-11e5-8359-f2b5b5c6a094.JPG)

**Comment by rkrejci** [comment]
Can you provide the data you are validating?

**Comment by hiharikp** [comment]
First Set of models (augment in student)
================================

![config_data_augment](https://cloud.githubusercontent.com/assets/13743705/9194801/97d824ea-403b-11e5-8d59-9ca71696c85f.JPG)

**Comment by hiharikp** [comment]
Second set of models (no augmentation)
================================

![config_data_noaugment](https://cloud.githubusercontent.com/assets/13743705/9194976/0ad82502-403d-11e5-805b-8dd030fd98bd.JPG)

**Comment by rkrejci** [comment]
I see the problem now - it is the problem of the libnetconf datastore design, dividing datastore (data) into a separated parts according to a main data model.

1) Augment case
There are 2 ways to load the modules into the server.

The first I've tried is only to specify the student module as augment to college. In this case I got the error already on the first edit-config setting the student's name. The reason is that libnetconf does not expect a top level (students) element with a different namespace from the `http://www.abc.com/ns/college`.

The second way, you probably used, is to have two datastore parts - one for college and another for students. In that case, the first edit-config succeeds, but the data are stored in a standalone libnetconf datastore part. That's the reason why the second edit-config fails, libnetconf validates datastore parts separately, so when it validates the college datastore part, it does not see the students data.

2) No augmentation case
Here it is actually the same as the second part of 1) - libnetconf does not see the data from another datastore part.

The design of datastore parts in libnetconf follows the idea of separated modules you can add/remove on the fly. Another problem is that this allows developers to generate validators files only for a specific module. If libnetconf would validate all the data at once, the validators files would have to be generated for all the used modules.

The only solution/hack I have for you at this moment is to modify the student module to not have a top level container students, but just augmenting the college module:
```
module student {

    namespace "http://www.abc.com/ns/student";
    prefix "stud";

    import college {
        prefix clg;
    }

    organization
    "TBD";

    revision 2014-09-18 {
        description "Initial revision.";
    }

    typedef stud-name-ref {
        type leafref {
            path "/clg:college-info/stud:students/stud:student/stud:name";
        }
    }

    augment "/clg:college-info" {
        container students {
            list student {
                key name;
                leaf name {
                    type string;
                }
            }
        }
    }

    augment "/clg:college-info/clg:award-info" {
        leaf best-student-name {
            type stud:stud-name-ref;
        }
    }
}
```

In case of the netopeer-server, the configuration file may looks like this:
```
<?xml version="1.0" ?>
<device>
  <name>college</name>
  <data-models>
    <model-main><path>/some/path/college.yin</path><feature>*</feature></model-main>
    <model><path>/some/path/student.yin</path><feature>*</feature></model>
  </data-models>
  <repo>
    <type>file</type>
    <path>/some/path/datastore.xml</path>
  </repo>
</device>
```

The problem should be solved in libnetconf2, where the data will be validated internally using libyang.
