### ISSUE TITLE
Question about when statement

### ISSUE THREAD

**Issue by classcwnd** [CESNET/libnetconf#94]
It seems that libnetconf doesn't support when statement.
We have following YANG mode segment. 
If we didn't configure ```multihop``` but configure ```ttl```, the validation is failed by libxml2. 
But if neither ```multihop``` nor ```ttl``` are configured (the validation is passed by libxml2), the default values of ```ttl```'s leafs are added to datastore. This is un-expected.
I think it is because libnetconf doesn't support when statement.
How can we handle this case or do we have workaround to bypass it? 
Is that possible for libnetconf to support when statement?

Yang model segment:
```
list neighbor {
  key "neighbor-choice";
  description   "BFD Neighbor ";
  leaf neighbor-choice {
    type union {
      type inet:ipv6-address;
      type inet:ipv4-address;
    }
    description "";
  }
  leaf multihop {
    type string;
    description "Multihop session Interface ";
  }

  container ttl {
    when "../multihop" {
      description "";
    }
    description "Time-to-live ";
    leaf minimum-accepted {
      type uint8 {
        range "1..255";
      }
      default "1";
      description "Minimum ttl accepted in received BFD "
      + "packets Specify minimum ttl accepted in received BFD "
      + "packets ";
    }
    leaf ttl-value {
      type uint8 {
        range "1..255";
      }
      default "255";
      description "Specify ttl for transmitted BFD packets ";
    }
  }
}
```

**Comment by rkrejci** [comment]
You are right, the `when` statement is not supported by libnetconf itself, it is only checked by external validators (I believe by schematron in this case). The similar issue can probably appear also with the `must` restrictions.

The problem here is with adding default values - the functionality ignores the `when` restriction and before passing configuration data into the transAPI module, the default values are added into the data tree (the same is done when you call get-config in netopeer-cli with  `--defaults report-all-tagged` option).

I think that the with-default part in libnetconf could be extended to handle `when` restrictions. However, since this will be supported by libyang (and therefore by libnetconf2) I'm not going to implement it. Anyway, I would accept patches solving this issue in current libnetconf.

**Comment by classcwnd** [comment]
Will you have a plan to give a patch to current libnetconf?

**Comment by rkrejci** [comment]
If you or someone else will provide the patch, then I can patch the current libnetconf. As I wrote, I'm not going to implement it, but I will welcome if someone would provide the patch.

libnetconf2 will support `when` statement because of using libyang.
